# 此文件由makelocal.sh自动生成
MAKEFILE_POSTFIX=.Linux
# 此文件由makeobj.sh自动生成
############################################################
# 项目名 : 
# 模块名 : 
# 备  注 : 
############################################################

###### 源文件配置区
# 编译宏
AR		=	ar
AFLAGS		=	rv
SOFLAGS		=	-shared
ESOFLAGS	=	

# c源代码文件宏及推导规则
CC		=	gcc -g -fPIC -O2 -Wall -Werror -fno-strict-aliasing
CC_NOWARN	=	gcc -g -fPIC -O2

c_FILE_o	=	$(c_FILE:.c=.o)
c_FILE2_o	=	$(c_FILE2:.c=.o)
c_FILE3_o	=	$(c_FILE3:.c=.o)
c_FILE4_o	=	$(c_FILE4:.c=.o)
c_FILE5_o	=	$(c_FILE5:.c=.o)
c_FILE_CLEAN	=	$(c_FILE_o) $(c_FILE2_o) $(c_FILE3_o) $(c_FILE4_o) $(c_FILE5_o)

.SUFFIXES:.c
.c.o	:
	$(CC) $(CFLAGS) -c $<

c_FILE		=	\
			test_hello.c \
			test_demo.c \
			test_stylesfunc.c \
			test_outputfunc.c \
			test_press.c \
			test_press_noclose.c \
			test_press_mpt.c \
			test_press_mpt_tls.c \
			test_memoryleak.c \
			test_funny.c \
			test_logconf.c \
			test_logsconf.c \
			test_afterrotatefile.c \
			test_filterlogfunc.c \
			test_logc.c \

###### 目标文件、安装目录配置区
BIN		=	$(c_FILE:.c=)

###### 编译选项
CFLAGS		=	-I. \
			-I../src \

###### 链接选项
LFLAGS		=	-L. \
			-L../src \
			-liLOG3 \
			-lpthread \

###### 额外宏定义区
CLEAN_ADDITION	=	LOGC.o

###### 加载mktpl模板库
# 最终目标列表
all	:	$(OBJ) $(OBJ2) $(LIB) $(LIB2) $(SQL) $(NOINST_OBJ) $(BIN) $(BIN2)

# 文件系统宏
CD		=	cd
RM		=	rm -f
CP		=	cp -rf
MV		=	mv -f
MKDIR		=	mkdir -p

# 预定义源文件清理删除关联宏
_FILE_CLEAN	=	$(c_FILE_CLEAN) $(cpp_FILE_CLEAN) $(SQC_FILE_CLEAN) $(ec_FILE_CLEAN) $(ec_FILE2_CLEAN) $(csm_FILE_CLEAN) $(c_html_FILE_CLEAN) $(cui_FILE_CLEAN) $(dtd_FILE_CLEAN) $(prt_FILE_CLEAN) $(fmd_FILE_CLEAN) $(smd_FILE_CLEAN) $(def_FILE_CLEAN) $(act_FILE_CLEAN) $(sml2c_FILE_CLEAN)

# 清理删除规则
.PHONY:clean
clean		:
	@for FILE in $(_FILE_CLEAN) $(BIN) $(BIN2) $(LIB) $(LIB2) $(OBJ) $(OBJ2) $(NOINST_OBJ) $(CLEAN_ADDITION) ; do \
		echo $(RM) $$FILE ; \
		$(RM) $$FILE ; \
	done


# 预定义源代码缺省头文件宏
DFTHDER		=	$(csm_FILE_DFTHDER) $(cui_FILE_DFTHDER) $(dtd_FILE_DFTHDER) $(prt_FILE_DFTHDER) $(fmd_FILE_DFTHDER) $(smd_FILE_DFTHDER) $(def_FILE_DFTHDER) $(act_FILE_DFTHDER) $(sml2c_FILE_DFTHDER)

# 提交安装规则
.PHONY:install
install		:	all

ifneq ($(strip $(BININST)),)
	@if [ ! -d "$(BININST)" ] ; then \
		echo $(MKDIR) $(BININST) ; \
		$(MKDIR) $(BININST) ; \
	fi
ifneq ($(strip $(BIN)),)
	@for FILE in `echo $(BIN)` ; do \
		if [ -f $(BININST)/$$FILE ] ; then \
			echo $(RM) $(BININST)/$$FILE ; \
			$(RM) $(BININST)/$$FILE ; \
		fi ; \
		if [ -f $$FILE ] ; then \
			echo $(CP) $$FILE $(BININST)/ ; \
			$(CP) $$FILE $(BININST)/ ; \
		fi ; \
	done
endif
endif
ifneq ($(strip $(BININST2)),)
	@if [ ! -d "$(BININST2)" ] ; then \
		echo $(MKDIR) $(BININST2) ; \
		$(MKDIR) $(BININST2) ; \
	fi
ifneq ($(strip $(BIN2)),)
	@for FILE in `echo $(BIN2)` ; do \
		if [ -f $(BININST2)/$$FILE ] ; then \
			echo $(RM) $(BININST2)/$$FILE ; \
			$(RM) $(BININST2)/$$FILE ; \
		fi ; \
		if [ -f $$FILE ] ; then \
			echo $(CP) $$FILE $(BININST2)/ ; \
			$(CP) $$FILE $(BININST2)/ ; \
		fi ; \
	done
endif
endif

ifneq ($(strip $(DFTHDERINST)),)
	@if [ ! -d "$(DFTHDERINST)" ] ; then \
		echo $(MKDIR) $(DFTHDERINST) ; \
		$(MKDIR) $(DFTHDERINST) ; \
	fi
ifneq ($(strip $(DFTHDER)),)
	@for FILE in `echo $(DFTHDER)` ; do \
		if [ -f $(DFTHDERINST)/$$FILE ] ; then \
			echo $(RM) $(DFTHDERINST)/$$FILE ; \
			$(RM) $(DFTHDERINST)/$$FILE ; \
		fi ; \
		if [ -f $$FILE ] ; then \
			echo $(CP) $$FILE $(DFTHDERINST)/ ; \
			$(CP) $$FILE $(DFTHDERINST)/ ; \
		fi ; \
	done
endif
endif



###### 目标文件依赖关系
test_hello		:	test_hello.o
	$(CC) -o $@ test_hello.o $(LFLAGS)

test_demo		:	test_demo.o
	$(CC) -o $@ test_demo.o $(LFLAGS)

test_press		:	test_press.o
	$(CC) -o $@ test_press.o $(LFLAGS)

test_press_noclose	:	test_press_noclose.o
	$(CC) -o $@ test_press_noclose.o $(LFLAGS)

test_press_mpt		:	test_press_mpt.o
	$(CC) -o $@ test_press_mpt.o $(LFLAGS)

test_press_mpt_tls	:	test_press_mpt_tls.o
	$(CC) -o $@ test_press_mpt_tls.o $(LFLAGS)

test_stylesfunc		:	test_stylesfunc.o
	$(CC) -o $@ test_stylesfunc.o $(LFLAGS)

test_outputfunc		:	test_outputfunc.o
	$(CC) -o $@ test_outputfunc.o $(LFLAGS)

test_memoryleak		:	test_memoryleak.o
	$(CC) -o $@ test_memoryleak.o $(LFLAGS)

test_funny		:	test_funny.o
	$(CC) -o $@ test_funny.o $(LFLAGS)

test_logconf		:	test_logconf.o
	$(CC) -o $@ test_logconf.o $(LFLAGS)

test_logsconf		:	test_logsconf.o
	$(CC) -o $@ test_logsconf.o $(LFLAGS)

test_afterrotatefile	:	test_afterrotatefile.o
	$(CC) -o $@ test_afterrotatefile.o $(LFLAGS)

test_filterlogfunc	:	test_filterlogfunc.o
	$(CC) -o $@ test_filterlogfunc.o $(LFLAGS)

bench_tiny		:	bench_tiny.o
	$(CC) -o $@ bench_tiny.o $(LFLAGS)

LOGC.o			:	../src/LOGC.c
	$(CC) $(CFLAGS) -c ../src/LOGC.c

test_logc		:	test_logc.o LOGC.o
	$(CC) -o $@ test_logc.o LOGC.o -lpthread

