# 此文件由makelocal.sh自动生成
MAKEFILE_POSTFIX=.WINDOWS-MinGW
# 此文件由makeobj.sh自动生成
############################################################
# 项目名 : 
# 模块名 : 
# 备  注 : 
############################################################

###### 源文件配置区
# 编译宏
AR		=	ar
AFLAGS		=	rv
SOFLAGS		=	-shared -fPIC
ESOFLAGS	=	

# c源代码文件宏及推导规则
CC		=	gcc -g -fPIC -Wall -Werror -O2
CC_NOWARN	=	gcc -g -fPIC -O2

c_FILE_o	=	$(c_FILE:.c=.o)
c_FILE2_o	=	$(c_FILE2:.c=.o)
c_FILE3_o	=	$(c_FILE3:.c=.o)
c_FILE4_o	=	$(c_FILE4:.c=.o)
c_FILE5_o	=	$(c_FILE5:.c=.o)
c_FILE_CLEAN	=	$(c_FILE_o) $(c_FILE2_o) $(c_FILE3_o) $(c_FILE4_o) $(c_FILE5_o)

.SUFFIXES:.c
.c.o	:
	$(CC) $(CFLAGS) -c $<

c_FILE		=	\
			test_logconf_kvfile.c \
			test_logsconf_kvfile.c \

###### 目标文件、安装目录配置区
BIN		=	$(c_FILE:.c=)

###### 编译选项
CFLAGS		=	-I. \
			-I../src \
			-I../src-conf-kvfile \
			-std=gnu99 \

###### 链接选项
LFLAGS		=	-L. \
			-L../src-conf-kvfile \
			-liLOG3CONF_KVFILE \
			-L../src \
			-liLOG3 \
			-lpthread \

###### 额外宏定义区
CLEAN_ADDITION	=

###### 加载mktpl模板库
# 最终目标列表
all	:	$(OBJ) $(OBJ2) $(LIB) $(LIB2) $(SQL) $(NOCLEAN_OBJ) $(NOINST_OBJ) $(BIN) $(BIN2)

prepro_all	:	$(PREPRO)


# 文件系统宏
CD		=	cd
RM		=	del
CP		=	mcopy
MV		=	move
MKDIR		=	mkdir

# 预定义源文件清理删除关联宏
_FILE_CLEAN	=	$(c_FILE_CLEAN) $(cpp_FILE_CLEAN) $(SQC_FILE_CLEAN) $(ec_FILE_CLEAN) $(ec_FILE2_CLEAN) $(csm_FILE_CLEAN) $(c_html_FILE_CLEAN) $(cui_FILE_CLEAN) $(dtd_FILE_CLEAN) $(prt_FILE_CLEAN) $(fmd_FILE_CLEAN) $(smd_FILE_CLEAN) $(def_FILE_CLEAN) $(act_FILE_CLEAN)

# 清理删除规则
clean		:
	$(RM) $(_FILE_CLEAN) $(BIN) $(BIN2) $(LIB) $(LIB2) $(OBJ) $(OBJ2) $(NOINST_OBJ) $(CLEAN_ADDITION)


# 预定义源代码缺省头文件宏
DFTHDER		=	$(csm_FILE_DFTHDER) $(cui_FILE_DFTHDER) $(dtd_FILE_DFTHDER) $(prt_FILE_DFTHDER) $(fmd_FILE_DFTHDER) $(smd_FILE_DFTHDER) $(def_FILE_DFTHDER) $(act_FILE_DFTHDER)

# 提交安装规则
install		:	all

ifneq ($(strip $(BIN)),)
ifneq ($(strip $(BININST)),)
	-$(MKDIR) "$(BININST)"
	$(CP) $(BIN) "$(BININST)/"
endif
endif
ifneq ($(strip $(BIN2)),)
ifneq ($(strip $(BININST2)),)
	-$(MKDIR) "$(BININST2)"
	$(CP) $(BIN2) "$(BININST2)/"
endif
endif

ifneq ($(strip $(DFTHDER)),)
ifneq ($(strip $(DFTHDERINST)),)
	-$(MKDIR) "$(DFTHDERINST)"
	$(CP) $(DFTHDER) "$(DFTHDERINST)/"
endif
endif



###### 目标文件依赖关系
test_logconf_kvfile		:	test_logconf_kvfile.o
	$(CC) -o $@ test_logconf_kvfile.o $(LFLAGS)

test_logsconf_kvfile		:	test_logsconf_kvfile.o
	$(CC) -o $@ test_logsconf_kvfile.o $(LFLAGS)

